apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-cq5gsn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cq5gsn
  namespace: my-nginx-cq5gsn
  labels:
    name: nginx-cq5gsn
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-cq5gsn
  template:
    metadata:
      namespace: my-nginx-cq5gsn
      labels:
        name: nginx-cq5gsn
    spec:
      containers:
      - name: nginx-cq5gsn
        image: nginx
        ports:
        - containerPort: 80

